name: loading_card
description: A new flutter package project.
version: 0.0.3
author: Adrian Avram <Adrian_Avram@Outlook.com>
homepage: https://github.com/SurrealShock/loading

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=2.0.0-dev.48 <3.0.0'